export const TEMPLATES = [
  {
    id: 1,
    name: "Neurológica",
    fields: [
      { fieldName: "Queixa Principal", label: "Queixa Principal", fieldType: "STRING", required: true },
      { fieldName: "painLevel", label: "Nível de Dor", fieldType: "NUMBER", required: false },
      { fieldName: "date", label: "Data", fieldType: "DATE", required: true },
      { fieldName: "hmp", label: "H.M.P", fieldType: "STRING", required: false },
      { fieldName: "hma", label: "H.M.A", fieldType: "STRING", required: false },
      { fieldName: "associatedConditions", label: "Condições Associadas", fieldType: "STRING", required: false },
      { fieldName: "allergy", label: "Alergia", fieldType: "BOOLEAN", required: false },
      { fieldName: "enzymeDeficiencyG6PD", label: "Deficiência Enzimática G6PD", fieldType: "BOOLEAN", required: false },
      { fieldName: "sinusitis", label: "Sinusite", fieldType: "BOOLEAN", required: false },
      { fieldName: "rhinitis", label: "Rinite", fieldType: "BOOLEAN", required: false },
      { fieldName: "diabetesMellitus", label: "Diabetes Mellitus", fieldType: "BOOLEAN", required: false },
      { fieldName: "highBloodPressure", label: "Hipertensão", fieldType: "BOOLEAN", required: false },
      { fieldName: "cardiopathy", label: "Cardiopatia", fieldType: "BOOLEAN", required: false },
      { fieldName: "anemia", label: "Anemia", fieldType: "BOOLEAN", required: false },
      { fieldName: "hyperthyroidism", label: "Hipertireoidismo", fieldType: "BOOLEAN", required: false },
      { fieldName: "epilepsyOrSeizures", label: "Epilepsia/Convulsões", fieldType: "BOOLEAN", required: false },
      { fieldName: "mentalDisorder", label: "Transtorno Mental", fieldType: "BOOLEAN", required: false },
      { fieldName: "recentCovidVaccine", label: "Vacina Covid Recente", fieldType: "BOOLEAN", required: false },
      { fieldName: "recentHemorrhage", label: "Hemorragia Recente", fieldType: "BOOLEAN", required: false },
      { fieldName: "physicalActivity", label: "Atividade Física", fieldType: "STRING", required: false },
      { fieldName: "pastSurgeries", label: "Cirurgias Anteriores", fieldType: "STRING", required: false },
      { fieldName: "fractures", label: "Fraturas", fieldType: "STRING", required: false },
      { fieldName: "smoking", label: "Fumante", fieldType: "BOOLEAN", required: false },
      { fieldName: "alcohol", label: "Álcool", fieldType: "BOOLEAN", required: false },
      { fieldName: "medications", label: "Medicações", fieldType: "STRING", required: false },
      { fieldName: "Inspeção - Pele", fieldType: "STRING", required: true },
      { fieldName: "Inspeção - Aspecto", fieldType: "STRING", required: true },
      { fieldName: "Inspeção - Deformidades", fieldType: "STRING", required: true },
      { fieldName: "Marcha", fieldType: "STRING", required: true },
      { fieldName: "Trocas Posturais", fieldType: "STRING", required: true },
      { fieldName: "AVDs (Atividades da Vida Diária)", fieldType: "STRING", required: false },
      { fieldName: "Observações", fieldType: "STRING", required: false },
      { fieldName: "weight", label: "Peso", fieldType: "NUMBER", required: false },
      { fieldName: "height", label: "Altura", fieldType: "NUMBER", required: false },
      { fieldName: "heartRate", label: "Frequência Cardíaca (FC)", fieldType: "STRING", required: false },
      { fieldName: "respiratoryRate", label: "Frequência Respiratória (FR)", fieldType: "STRING", required: false }
    ]
  },
  {
    id: 2,
    name: "Postural",
    fields: [
      { fieldName: "Queixa Principal", label: "Queixa Principal", fieldType: "STRING", required: true },
      { fieldName: "painLevel", label: "Nível de Dor", fieldType: "NUMBER", required: false },
      { fieldName: "date", label: "Data", fieldType: "DATE", required: true },
      { fieldName: "hmp", label: "H.M.P", fieldType: "STRING", required: false },
      { fieldName: "hma", label: "H.M.A", fieldType: "STRING", required: false },
      { fieldName: "associatedConditions", label: "Condições Associadas", fieldType: "STRING", required: false },
      { fieldName: "allergy", label: "Alergia", fieldType: "BOOLEAN", required: false },
      { fieldName: "enzymeDeficiencyG6PD", label: "Deficiência Enzimática G6PD", fieldType: "BOOLEAN", required: false },
      { fieldName: "sinusitis", label: "Sinusite", fieldType: "BOOLEAN", required: false },
      { fieldName: "rhinitis", label: "Rinite", fieldType: "BOOLEAN", required: false },
      { fieldName: "diabetesMellitus", label: "Diabetes Mellitus", fieldType: "BOOLEAN", required: false },
      { fieldName: "highBloodPressure", label: "Hipertensão", fieldType: "BOOLEAN", required: false },
      { fieldName: "cardiopathy", label: "Cardiopatia", fieldType: "BOOLEAN", required: false },
      { fieldName: "anemia", label: "Anemia", fieldType: "BOOLEAN", required: false },
      { fieldName: "hyperthyroidism", label: "Hipertireoidismo", fieldType: "BOOLEAN", required: false },
      { fieldName: "epilepsyOrSeizures", label: "Epilepsia/Convulsões", fieldType: "BOOLEAN", required: false },
      { fieldName: "mentalDisorder", label: "Transtorno Mental", fieldType: "BOOLEAN", required: false },
      { fieldName: "recentCovidVaccine", label: "Vacina Covid Recente", fieldType: "BOOLEAN", required: false },
      { fieldName: "recentHemorrhage", label: "Hemorragia Recente", fieldType: "BOOLEAN", required: false },
      { fieldName: "physicalActivity", label: "Atividade Física", fieldType: "STRING", required: false },
      { fieldName: "pastSurgeries", label: "Cirurgias Anteriores", fieldType: "STRING", required: false },
      { fieldName: "fractures", label: "Fraturas", fieldType: "STRING", required: false },
      { fieldName: "smoking", label: "Fumante", fieldType: "BOOLEAN", required: false },
      { fieldName: "alcohol", label: "Álcool", fieldType: "BOOLEAN", required: false },
      { fieldName: "medications", label: "Medicações", fieldType: "STRING", required: false },
      { fieldName: "Marcha", fieldType: "STRING", required: false },
      { fieldName: "Vista Anterior", fieldType: "STRING", required: false },
      { fieldName: "Vista Lateral Direita", fieldType: "STRING", required: false },
      { fieldName: "Vista Lateral Esquerda", fieldType: "STRING", required: false },
      { fieldName: "Vista Posterior", fieldType: "STRING", required: false },
      { fieldName: "Flexão Anterior Lateral", fieldType: "STRING", required: false },
      { fieldName: "Flexão Anterior A.P", fieldType: "STRING", required: false },
      { fieldName: "Postura de Trabalho - Sentada (Horas)", fieldType: "STRING", required: false },
      { fieldName: "Postura de Trabalho - Em Pé (Horas)", fieldType: "STRING", required: false },
      { fieldName: "weight", label: "Peso", fieldType: "NUMBER", required: false },
      { fieldName: "height", label: "Altura", fieldType: "NUMBER", required: false },
      { fieldName: "heartRate", label: "Frequência Cardíaca (FC)", fieldType: "STRING", required: false },
      { fieldName: "respiratoryRate", label: "Frequência Respiratória (FR)", fieldType: "STRING", required: false }
    ]
  },
  {
    id: 3,
    name: "Ortopédica",
    fields: [
      { fieldName: "Queixa Principal", label: "Queixa Principal", fieldType: "STRING", required: true },
      { fieldName: "painLevel", label: "Nível de Dor", fieldType: "NUMBER", required: false },
      { fieldName: "date", label: "Data", fieldType: "DATE", required: true },
      { fieldName: "hmp", label: "HMP", fieldType: "STRING", required: false },
      { fieldName: "hma", label: "HMA", fieldType: "STRING", required: false },
      { fieldName: "associatedConditions", label: "Condições Associadas", fieldType: "STRING", required: false },
      { fieldName: "allergy", label: "Alergia", fieldType: "BOOLEAN", required: false },
      { fieldName: "enzymeDeficiencyG6PD", label: "Deficiência Enzimática G6PD", fieldType: "BOOLEAN", required: false },
      { fieldName: "sinusitis", label: "Sinusite", fieldType: "BOOLEAN", required: false },
      { fieldName: "rhinitis", label: "Rinite", fieldType: "BOOLEAN", required: false },
      { fieldName: "diabetesMellitus", label: "Diabetes Mellitus", fieldType: "BOOLEAN", required: false },
      { fieldName: "highBloodPressure", label: "Pressão Alta", fieldType: "BOOLEAN", required: false },
      { fieldName: "cardiopathy", label: "Cardiopatia", fieldType: "BOOLEAN", required: false },
      { fieldName: "anemia", label: "Anemia", fieldType: "BOOLEAN", required: false },
      { fieldName: "hyperthyroidism", label: "Hipertireoidismo", fieldType: "BOOLEAN", required: false },
      { fieldName: "epilepsyOrSeizures", label: "Epilepsia ou Convulsões", fieldType: "BOOLEAN", required: false },
      { fieldName: "mentalDisorder", label: "Transtorno Mental", fieldType: "BOOLEAN", required: false },
      { fieldName: "recentCovidVaccine", label: "Vacina COVID Recente", fieldType: "BOOLEAN", required: false },
      { fieldName: "recentHemorrhage", label: "Hemorragia Recente", fieldType: "BOOLEAN", required: false },
      { fieldName: "physicalActivity", label: "Atividade Física", fieldType: "STRING", required: false },
      { fieldName: "pastSurgeries", label: "Cirurgias Anteriores", fieldType: "STRING", required: false },
      { fieldName: "fractures", label: "Fraturas", fieldType: "STRING", required: false },
      { fieldName: "smoking", label: "Tabagismo", fieldType: "BOOLEAN", required: false },
      { fieldName: "alcohol", label: "Álcool", fieldType: "BOOLEAN", required: false },
      { fieldName: "medications", label: "Medicações", fieldType: "STRING", required: false },
      { fieldName: "Circunferência - Direita", label: "Circunferência - Direita", fieldType: "NUMBER", required: true },
      { fieldName: "Circunferência - Esquerda", label: "Circunferência - Esquerda", fieldType: "NUMBER", required: true },
      { fieldName: "Força Muscular (F.M.) - Direita", label: "Força Muscular (F.M.) - Direita", fieldType: "NUMBER", required: true },
      { fieldName: "Força Muscular (F.M.) - Esquerda", label: "Força Muscular (F.M.) - Esquerda", fieldType: "NUMBER", required: true },
      { fieldName: "ADM - Direita", label: "ADM - Direita", fieldType: "NUMBER", required: true },
      { fieldName: "ADM - Esquerda", label: "ADM - Esquerda", fieldType: "NUMBER", required: true },
      { fieldName: "weight", label: "Peso", fieldType: "NUMBER", required: false },
      { fieldName: "height", label: "Altura", fieldType: "NUMBER", required: false },
      { fieldName: "heartRate", label: "Frequência Cardíaca (FC)", fieldType: "STRING", required: false },
      { fieldName: "respiratoryRate", label: "Frequência Respiratória (FR)", fieldType: "STRING", required: false }
    ]
  },
  {
    id: 4,
    name: "Facial",
    fields: [
      { fieldName: "Queixa Principal", label: "Queixa Principal", fieldType: "STRING", required: true },
      { fieldName: "painLevel", label: "Nível de Dor", fieldType: "NUMBER", required: false },
      { fieldName: "date", label: "Data", fieldType: "DATE", required: true },
      { fieldName: "hmp", label: "HMP", fieldType: "STRING", required: false },
      { fieldName: "hma", label: "HMA", fieldType: "STRING", required: false },
      { fieldName: "associatedConditions", label: "Condições Associadas", fieldType: "STRING", required: false },
      { fieldName: "allergy", label: "Alergia", fieldType: "BOOLEAN", required: false },
      { fieldName: "enzymeDeficiencyG6PD", label: "Deficiência Enzimática G6PD", fieldType: "BOOLEAN", required: false },
      { fieldName: "sinusitis", label: "Sinusite", fieldType: "BOOLEAN", required: false },
      { fieldName: "rhinitis", label: "Rinite", fieldType: "BOOLEAN", required: false },
      { fieldName: "diabetesMellitus", label: "Diabetes Mellitus", fieldType: "BOOLEAN", required: false },
      { fieldName: "highBloodPressure", label: "Pressão Alta", fieldType: "BOOLEAN", required: false },
      { fieldName: "cardiopathy", label: "Cardiopatia", fieldType: "BOOLEAN", required: false },
      { fieldName: "anemia", label: "Anemia", fieldType: "BOOLEAN", required: false },
      { fieldName: "hyperthyroidism", label: "Hipertireoidismo", fieldType: "BOOLEAN", required: false },
      { fieldName: "epilepsyOrSeizures", label: "Epilepsia ou Convulsões", fieldType: "BOOLEAN", required: false },
      { fieldName: "mentalDisorder", label: "Transtorno Mental", fieldType: "BOOLEAN", required: false },
      { fieldName: "recentCovidVaccine", label: "Vacina COVID Recente", fieldType: "BOOLEAN", required: false },
      { fieldName: "recentHemorrhage", label: "Hemorragia Recente", fieldType: "BOOLEAN", required: false },
      { fieldName: "physicalActivity", label: "Atividade Física", fieldType: "STRING", required: false },
      { fieldName: "pastSurgeries", label: "Cirurgias Anteriores", fieldType: "STRING", required: false },
      { fieldName: "fractures", label: "Fraturas", fieldType: "STRING", required: false },
      { fieldName: "smoking", label: "Tabagismo", fieldType: "BOOLEAN", required: false },
      { fieldName: "alcohol", label: "Álcool", fieldType: "BOOLEAN", required: false },
      { fieldName: "medications", label: "Medicações", fieldType: "STRING", required: false },
      { fieldName: "Tem algum problema de saúde? Qual?", label: "Tem algum problema de saúde? Qual?", fieldType: "STRING", required: false },
      { fieldName: "Ingestão de água. Quantos Litros no dia?", label: "Ingestão de água. Quantos Litros no dia?", fieldType: "STRING", required: false },
      { fieldName: "Exposição ao sol e cuidados", label: "Exposição ao sol e cuidados", fieldType: "STRING", required: false },
      { fieldName: "Uso de filtro solar (frequência e tipo)", label: "Uso de filtro solar (frequência e tipo)", fieldType: "STRING", required: false },
      { fieldName: "Lentes de contato?", label: "Lentes de contato?", fieldType: "STRING", required: false },
      { fieldName: "Cosméticos / dermocosméticos utilizados", label: "Cosméticos / dermocosméticos utilizados", fieldType: "STRING", required: false },
      { fieldName: "Tratamentos estéticos anteriores", label: "Tratamentos estéticos anteriores", fieldType: "STRING", required: false },
      { fieldName: "FEG (Gordurosa, Fibrosa, Flácida) - Em qual região?", label: "FEG (Gordurosa, Fibrosa, Flácida) - Em qual região?", fieldType: "STRING", required: false },
      { fieldName: "Flacidez (Tissular e Muscular) - Em qual região?", label: "Flacidez (Tissular e Muscular) - Em qual região?", fieldType: "STRING", required: false },
      { fieldName: "Condições da pele (Cravos, Acne, Cicatriz, Manchas)", label: "Condições da pele (Cravos, Acne, Cicatriz, Manchas)", fieldType: "STRING", required: false },
      { fieldName: "O que você espera do tratamento?", label: "O que você espera do tratamento?", fieldType: "STRING", required: false },
      { fieldName: "weight", label: "Peso", fieldType: "NUMBER", required: false },
      { fieldName: "height", label: "Altura", fieldType: "NUMBER", required: false },
      { fieldName: "heartRate", label: "Frequência Cardíaca (FC)", fieldType: "STRING", required: false },
      { fieldName: "respiratoryRate", label: "Frequência Respiratória (FR)", fieldType: "STRING", required: false }
    ]
  },
  {
    id: 5,
    name: "Corporal",
    fields: [
      { fieldName: "Queixa Principal", label: "Queixa Principal", fieldType: "STRING", required: true },
      { fieldName: "painLevel", label: "Nível de Dor", fieldType: "NUMBER", required: false },
      { fieldName: "date", label: "Data", fieldType: "DATE", required: true },
      { fieldName: "hmp", label: "HMP", fieldType: "STRING", required: false },
      { fieldName: "hma", label: "HMA", fieldType: "STRING", required: false },
      { fieldName: "associatedConditions", label: "Condições Associadas", fieldType: "STRING", required: false },
      { fieldName: "allergy", label: "Alergia", fieldType: "BOOLEAN", required: false },
      { fieldName: "enzymeDeficiencyG6PD", label: "Deficiência Enzimática G6PD", fieldType: "BOOLEAN", required: false },
      { fieldName: "sinusitis", label: "Sinusite", fieldType: "BOOLEAN", required: false },
      { fieldName: "rhinitis", label: "Rinite", fieldType: "BOOLEAN", required: false },
      { fieldName: "diabetesMellitus", label: "Diabetes Mellitus", fieldType: "BOOLEAN", required: false },
      { fieldName: "highBloodPressure", label: "Pressão Alta", fieldType: "BOOLEAN", required: false },
      { fieldName: "cardiopathy", label: "Cardiopatia", fieldType: "BOOLEAN", required: false },
      { fieldName: "anemia", label: "Anemia", fieldType: "BOOLEAN", required: false },
      { fieldName: "hyperthyroidism", label: "Hipertireoidismo", fieldType: "BOOLEAN", required: false },
      { fieldName: "epilepsyOrSeizures", label: "Epilepsia ou Convulsões", fieldType: "BOOLEAN", required: false },
      { fieldName: "mentalDisorder", label: "Transtorno Mental", fieldType: "BOOLEAN", required: false },
      { fieldName: "recentCovidVaccine", label: "Vacina COVID Recente", fieldType: "BOOLEAN", required: false },
      { fieldName: "recentHemorrhage", label: "Hemorragia Recente", fieldType: "BOOLEAN", required: false },
      { fieldName: "physicalActivity", label: "Atividade Física", fieldType: "STRING", required: false },
      { fieldName: "pastSurgeries", label: "Cirurgias Anteriores", fieldType: "STRING", required: false },
      { fieldName: "fractures", label: "Fraturas", fieldType: "STRING", required: false },
      { fieldName: "smoking", label: "Tabagismo", fieldType: "BOOLEAN", required: false },
      { fieldName: "alcohol", label: "Álcool", fieldType: "BOOLEAN", required: false },
      { fieldName: "medications", label: "Medicações", fieldType: "STRING", required: false },
      { fieldName: "Retenção de líquido", label: "Retenção de Líquido", fieldType: "BOOLEAN", required: false },
      { fieldName: "Gordura Localizada (região)", label: "Gordura Localizada (região)", fieldType: "STRING", required: false },
      { fieldName: "FEG (Edematosa/Gordurosa, Fibrótica, Flácida)", label: "FEG (Edematosa/Gordurosa, Fibrótica, Flácida)", fieldType: "STRING", required: false },
      { fieldName: "Flacidez (Tissular e Muscular)", label: "Flacidez (Tissular e Muscular)", fieldType: "STRING", required: false },
      { fieldName: "Estria (região)", label: "Estria (região)", fieldType: "STRING", required: false },
      { fieldName: "Altura", label: "Altura", fieldType: "STRING", required: false },
      { fieldName: "Peso", label: "Peso", fieldType: "STRING", required: false },
      { fieldName: "Frequência Respiratória (FR)", label: "Frequência Respiratória (FR)", fieldType: "STRING", required: false },
      { fieldName: "Frequência Cardíaca (FC)", label: "Frequência Cardíaca (FC)", fieldType: "STRING", required: false },
      { fieldName: "Abdomen", label: "Abdomen", fieldType: "STRING", required: false },
      { fieldName: "Braço Direito", label: "Braço Direito", fieldType: "STRING", required: false },
      { fieldName: "Braço Esquerdo", label: "Braço Esquerdo", fieldType: "STRING", required: false },
      { fieldName: "Tórax", label: "Tórax", fieldType: "STRING", required: false },
      { fieldName: "Cintura", label: "Cintura", fieldType: "STRING", required: false },
      { fieldName: "Flanco", label: "Flanco", fieldType: "STRING", required: false },
      { fieldName: "Quadril / Culote", label: "Quadril / Culote", fieldType: "STRING", required: false },
      { fieldName: "Coxa Sup. Direita", label: "Coxa Sup. Direita", fieldType: "STRING", required: false },
      { fieldName: "Coxa Sup. Esquerda", label: "Coxa Sup. Esquerda", fieldType: "STRING", required: false },
      { fieldName: "Coxa Inf. Direita", label: "Coxa Inf. Direita", fieldType: "STRING", required: false },
      { fieldName: "Coxa Inf. Esquerda", label: "Coxa Inf. Esquerda", fieldType: "STRING", required: false },
      { fieldName: "Peso", label: "Peso", fieldType: "STRING", required: false },
      { fieldName: "Observações", label: "Observações", fieldType: "STRING", required: false }
    ]
  },
  {
    id: 6,
    name: "Ozonioterapia",
    fields: [
      { fieldName: "Queixa Principal", label: "Queixa Principal", fieldType: "STRING", required: true },
      { fieldName: "painLevel", label: "Nível de Dor", fieldType: "NUMBER", required: false },
      { fieldName: "date", label: "Data", fieldType: "DATE", required: true },
      { fieldName: "hmp", label: "HMP", fieldType: "STRING", required: false },
      { fieldName: "hma", label: "HMA", fieldType: "STRING", required: false },
      { fieldName: "associatedConditions", label: "Condições Associadas", fieldType: "STRING", required: false },
      { fieldName: "allergy", label: "Alergia", fieldType: "BOOLEAN", required: false },
      { fieldName: "enzymeDeficiencyG6PD", label: "Deficiência Enzimática G6PD", fieldType: "BOOLEAN", required: false },
      { fieldName: "sinusitis", label: "Sinusite", fieldType: "BOOLEAN", required: false },
      { fieldName: "rhinitis", label: "Rinite", fieldType: "BOOLEAN", required: false },
      { fieldName: "diabetesMellitus", label: "Diabetes Mellitus", fieldType: "BOOLEAN", required: false },
      { fieldName: "highBloodPressure", label: "Pressão Alta", fieldType: "BOOLEAN", required: false },
      { fieldName: "cardiopathy", label: "Cardiopatia", fieldType: "BOOLEAN", required: false },
      { fieldName: "anemia", label: "Anemia", fieldType: "BOOLEAN", required: false },
      { fieldName: "hyperthyroidism", label: "Hipertireoidismo", fieldType: "BOOLEAN", required: false },
      { fieldName: "epilepsyOrSeizures", label: "Epilepsia ou Convulsões", fieldType: "BOOLEAN", required: false },
      { fieldName: "mentalDisorder", label: "Transtorno Mental", fieldType: "BOOLEAN", required: false },
      { fieldName: "recentCovidVaccine", label: "Vacina COVID Recente", fieldType: "BOOLEAN", required: false },
      { fieldName: "recentHemorrhage", label: "Hemorragia Recente", fieldType: "BOOLEAN", required: false },
      { fieldName: "physicalActivity", label: "Atividade Física", fieldType: "STRING", required: false },
      { fieldName: "pastSurgeries", label: "Cirurgias Anteriores", fieldType: "STRING", required: false },
      { fieldName: "fractures", label: "Fraturas", fieldType: "STRING", required: false },
      { fieldName: "smoking", label: "Tabagismo", fieldType: "BOOLEAN", required: false },
      { fieldName: "alcohol", label: "Álcool", fieldType: "BOOLEAN", required: false },
      { fieldName: "medications", label: "Medicações", fieldType: "STRING", required: false },
      { fieldName: "Tipo de Alimentação", label: "Tipo de Alimentação", fieldType: "STRING", required: false },
      { fieldName: "Ingestão de Água (Copos/dia)", label: "Ingestão de Água (Copos/dia)", fieldType: "STRING", required: false },
      { fieldName: "Funcionamento Intestinal", label: "Funcionamento Intestinal", fieldType: "STRING", required: false },
      { fieldName: "Sono/Repouso", label: "Sono/Repouso", fieldType: "STRING", required: false },
      { fieldName: "Sexualidade/Reprodução", label: "Sexualidade/Reprodução", fieldType: "STRING", required: false },
      { fieldName: "DUM", label: "DUM", fieldType: "DATE", required: false },
      { fieldName: "Postura de Trabalho - Sentada (Horas)", label: "Postura de Trabalho - Sentada (Horas)", fieldType: "STRING", required: false },
      { fieldName: "Postura de Trabalho - Em Pé (Horas)", label: "Postura de Trabalho - Em Pé (Horas)", fieldType: "STRING", required: false },
      { fieldName: "Tratamento com ozônio anterior - Qual via/conc.", label: "Tratamento com ozônio anterior - Qual via/conc.", fieldType: "STRING", required: false },
      { fieldName: "Tratamento estético anterior - Qual?", label: "Tratamento estético anterior - Qual?", fieldType: "STRING", required: false },
      { fieldName: "Planejamento Semanal", label: "Planejamento Semanal", fieldType: "STRING", required: false },
      { fieldName: "Observações", label: "Observações", fieldType: "STRING", required: false },
      { fieldName: "weight", label: "Peso", fieldType: "NUMBER", required: false },
      { fieldName: "height", label: "Altura", fieldType: "NUMBER", required: false },
      { fieldName: "heartRate", label: "Frequência Cardíaca (FC)", fieldType: "STRING", required: false },
      { fieldName: "respiratoryRate", label: "Frequência Respiratória (FR)", fieldType: "STRING", required: false }
    ]
  }
];